server:
  port: 9082
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 47.117.153.17:8848
    gateway:
      discovery:
        locator:
          enabled: true  # 开启通过服务名自动转发
          lower-case-service-id: true