spring:
  application:
    name: gateway-service
  config:
    import: nacos:gateway-service-dev.yml
  cloud:
    nacos:
      discovery:
        server-addr: 47.117.153.17:8848
      config:
        server-addr: 47.117.153.17:8848
        file-extension: yml
    gateway:
      discovery:
        locator:
          enabled: true  # 开启通过服务名自动转发
          lower-case-service-id: true