version: '3.8'

services:
  social-service:
    build:
      context: ./social-service
      dockerfile: Dockerfile
    ports:
      - "9084:9084"
    container_name: social-service
    networks:
      - tourlinkwork

  routing-service:
    build:
      context: ./routing-service
      dockerfile: Dockerfile
    ports:
      - "9083:9083"
    container_name: routing-service
    networks:
      - tourlinkwork

networks:
  tourlinkwork:

