services:
  nacos:
    image: nacos/nacos-server:v2.3.0
    container_name: nacos
    environment:
      - MODE=standalone
      - NACOS_APPLICATION_PORT=8848
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - ./nacos:/home/nacos/logs
    restart: always
    networks:
      - tourlinkwork
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8848/nacos" ]
      interval: 10s
      timeout: 5s
      retries: 10

  attraction-service:
    build:
      context: ./attraction-service
      dockerfile: Dockerfile
    ports:
      - "9080:9080"
    container_name: attraction-service
    networks:
      - tourlinkwork
    depends_on:
      nacos:
        condition: service_healthy

  data-platform-service:
    build:
      context: ./data-platform-service
      dockerfile: Dockerfile
    ports:
      - "9081:9081"
    container_name: data-platform-service
    networks:
      - tourlinkwork
    depends_on:
      nacos:
        condition: service_healthy

  routing-service:
    build:
      context: ./routing-service
      dockerfile: Dockerfile
    ports:
      - "9083:9083"
    container_name: routing-service
    networks:
      - tourlinkwork
    depends_on:
      nacos:
        condition: service_healthy

  social-service:
    build:
      context: ./social-service
      dockerfile: Dockerfile
    ports:
      - "9084:9084"
    container_name: social-service
    networks:
      - tourlinkwork
    depends_on:
      nacos:
        condition: service_healthy

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "9085:9085"
    container_name: user-service
    networks:
      - tourlinkwork
    depends_on:
      nacos:
        condition: service_healthy

networks:
  tourlinkwork:

